name: website
on[Push]
job: deploy_to_s3:
  run-on:ubuntu-latest
  steps:
    -name: Checkout Repository
     uses: action/checkout@v3

    -name: AWS credential
     uses: aws-action/configure-aws-credndentials@v2
     with: aws-secret-access-key:${{ secrets.access-token }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION:eu-central-1 }}

    -name: Push to AWS S3
     run aws s3 sync.s3://mys3bucketdevopsexam
          
